add custom props for i18n
alibaba/x-render pull request #663
Opened 2022-02-04 10:38 UTC by yinzhiqiang

增加custom props 来支持更改button 和action的中文。

2022-02-04 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/x-render?pullRequest=663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/x-render?pullRequest=663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/x-render?pullRequest=663) it.</sub>

2022-02-15 02:35 UTC, tw93 commented
这样实现看着不是很彻底，是不是需要直接对与全局的form-render增加一个英语多语言的模式，会清晰可维护一下 @siyi98 @yinzhiqiang

2022-02-15 02:46 UTC, yinzhiqiang commented
@tw93 我不是很清楚form-render对多语言的支持是否有自己的roadmap, 以及要使用哪种模式？因为我急着要用在英文UI中，所以我就这么改了。

2022-02-15 02:51 UTC, yinzhiqiang commented
@tw93 @siyi98 理论上多语言也可以看做为UI配置多一部分，所以从schema中修改应该也是合理的，就算提供全局的默认的多语言配置，也应该允许从schema覆盖。

2022-02-15 02:56 UTC, tw93 commented
> @tw93 @siyi98 理论上多语言也可以看做为UI配置多一部分，所以从schema中修改应该也是合理的，就算提供全局的默认的多语言配置，也应该允许从schema覆盖。

嗯嗯，赞同，不过这一块最近我们想想怎么弄比较好

2022-03-29 07:13 UTC, money5240 requested changes
docs/form-render/advanced/listDisplay.md

2022-05-05 09:56 UTC, closed without merging